use_frameworks!
platform :ios, '9.0'

target 'leetal-HGPlaceholders_Example' do
  pod 'leetal-HGPlaceholders', :path => '../'

  target 'leetal-HGPlaceholders_Tests' do
    inherit! :search_paths

    
  end
end
